# Generated by Django 4.2.7 on 2023-12-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
