# Generated by Django 4.2.7 on 2023-12-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
